---
spring:
  profiles: verb
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: subject

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: adjetive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: article

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: noun
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}
